name: CodeCov

on: [push, pull_request]

jobs:
  codecov:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - uses: checkout@v2
        with:
          fetch-depth: "2"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Requirements
        run: make setup
      - name: Generate Report
        run: make coverage-report
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
