name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
      - uses: checkout@v2
        with:
          fetch-depth: "2"

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install Requirements
        run: make setup
      - name: Generate Report
        run: make coverage-report
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
