name: CI

on:
  push:

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install Requirements
        run: make setup
      - name: Run Unit Tests
        run: make test-unit

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Requirements
        run: make setup
      - name: Run Integration Tests
        run: make test-integration

  test-e2e:
    name: End-to-end Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Requirements
        run: make setup
      - name: Run E2E Tests
        run: make test-end-to-end

  test-docs-build:
    name: Tests Docs Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Requirements
        run: make setup
      - name: Build Docs
        run: make docs-build

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    # only publish the docs when merging into main
    if: github.ref == 'refs/heads/main'
    # only attempt this, if building the docs was successful
    needs: test-docs-build
    steps:
      # check out repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: dev-requirements.txt
